# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170829_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
