# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20180420_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postit',
            old_name='user',
            new_name='user_id',
        ),
    ]
