# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20180509_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postit',
            old_name='user_id',
            new_name='user',
        ),
    ]
