# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_userid_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='posts/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.UserID')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileit',
            name='users',
        ),
        migrations.DeleteModel(
            name='FileIt',
        ),
    ]
